port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - name: Cloudflare Worker
    type: http
    server: restless-wildflower-7bb0.mahzood.workers.dev
    port: 80
